Switch Day-1 networking format proposal to nmstate
cybertron/enhancements pull request #1
Opened 2021-08-26 21:29 UTC by zaneb

Use nmstate instead of NetworkManager keyfiles as the user interface for
configuring pre-deploy baremetal host networking.

2021-08-26 21:29 UTC, zaneb commented
/cc @kirankt @hardys

2021-08-26 22:00 UTC, kirankt requested changes

2021-08-26 22:00 UTC, kirankt commented on enhancements/network/baremetal-ipi-network-configuration.md
> +  - name: eth0
This should actually be identical to the examples in nmstate repo and kubernetes-nmstate CR data, there are 3 top level fields: interfaces, dns-resolver, routes. So just adding the interface data won't cut it.

https://github.com/nmstate/nmstate/tree/base/examples
https://github.com/nmstate/kubernetes-nmstate/tree/main/docs/examples

```yaml
   interfaces:
   - name: br1
      type: linux-bridge
      state: up
      ipv4:
        dhcp: true
        enabled: true
   ...
   dns-resolver:
      config:
        search:
          ...
   routes:
      ...
```

2021-08-26 22:00 UTC, kirankt commented on enhancements/network/baremetal-ipi-network-configuration.md
> +          - name: eth0
ditto

2021-08-30 18:23 UTC, zaneb commented on enhancements/network/baremetal-ipi-network-configuration.md
> +  - name: eth0
Thanks, moved everything under 'interfaces:'.

2021-08-31 22:15 UTC, cybertron commented
lgtm. Let's see how this version goes over.

2021-08-31 22:16 UTC, merged